### ISSUE TITLE
ArgumentError (wrong number of arguments (3 for 0..2)):

### ISSUE THREAD

**Issue by eddiefisher** [gocardless/statesman#153]
I have error when I try to change status

my test repository: https://github.com/eddiefisher/statesman-test

```
Started PATCH "/payments/1" for ::1 at 2015-04-07 12:52:00 +0300
  ActiveRecord::SchemaMigration Load (0.5ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by PaymentsController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"bRlC741S78J0RvM67lxPQ2URCD01OykVJchRJNWRykvn1bQJyT4SXdF03BPEtUseG2zyJWay3YLXEHyptiz/eQ==", "payment"=>{"name"=>"test paymenta", "count"=>"1", "state"=>"confirmed"}, "commit"=>"Update Payment", "id"=>"1"}
  Payment Load (0.3ms)  SELECT  "payments".* FROM "payments" WHERE "payments"."id" = $1 LIMIT 1  [["id", 1]]
   (0.1ms)  BEGIN
   (0.1ms)  ROLLBACK
Completed 500 Internal Server Error in 59ms (ActiveRecord: 4.1ms)

ArgumentError (wrong number of arguments (3 for 0..2)):
  app/models/payment.rb:25:in `change_state'
  app/controllers/payments_controller.rb:44:in `block in update'
  app/controllers/payments_controller.rb:43:in `update'


  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_source.erb (7.0ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (4.2ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (79.5ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/_markup.html.erb (0.6ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.3ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/console.js.erb within layouts/javascript (62.4ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/main.js.erb within layouts/javascript (0.3ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/error_page.js.erb within layouts/javascript (0.5ms)
  Rendered /Users/eddifisher/.rvm/gems/ruby-2.2.0/gems/web-console-2.1.2/lib/web_console/templates/index.html.erb (145.7ms)
```

**Comment by Sinjo** [comment]
Just taken a quick look through the sample code. I'm not clear on how [this line](https://github.com/eddiefisher/statesman-test/blob/7f3d479721c84ded91540855141dced1c616045c/app/models/payment.rb#L25) could be passing 3 arguments into `transition_to!`. Also, as it is, this code has `attr_accessor :state` commented out, so wouldn't run.

Can you update the sample code to be exactly what's needed to cause the error?

**Comment by eddiefisher** [comment]
updated, now if you try to change state in payment you get error

**Comment by Sinjo** [comment]
Do you have the code which sends the HTTP request handy (`curl` sample would be fine)?

**Comment by eddiefisher** [comment]
I can do this at night, but now I'm at work

**Comment by Sinjo** [comment]
No problem. I'll check back in when you have the request available.

**Comment by fnando** [comment]
I had the same error last night. You're missing the storage configuration.

```ruby
# config/initializers/statesman.rb
Statesman.configure do
  storage_adapter(Statesman::Adapters::ActiveRecord)
end
```

**Comment by eddiefisher** [comment]
yep, you right, tnx =) I think it's need to be default settings or have generator

**Comment by eddiefisher** [comment]
I'm updated repository, now it's all working and I hope it's will help someone like example project

**Comment by greysteil** [comment]
Hey @eddiefisher, thanks for this. Would definitely be keen on a PR to make this error clearer.
