### ISSUE TITLE
`silence_stream` method was removed from Rails 5.

### ISSUE THREAD

**Issue by kenchan0130** [gocardless/statesman#229]
Hi,

When I run test this project, it failed.
Because it was installed Rails 5 removed the `silence_stream` method like this:

```
NoMethodError:
        undefined method `silence_stream' for #<RSpec::ExampleGroups::StatesmanAdaptersActiveRecordQueries::InState::GivenTheInitialState:0x007fe3cc10d148>
      # ./spec/spec_helper.rb:76:in `prepare_model_table'
      # ./spec/statesman/adapters/active_record_queries_spec.rb:5:in `block (2 levels) in <top (required)>'

  68) Statesman::Adapters::ActiveRecordQueries.in_state merging two queries
      Failure/Error:
        silence_stream(STDOUT) do
          CreateMyActiveRecordModelMigration.migrate(:up)
        end
```

I think about removing `silence_stream` method (and block).
How you do you feel about it?

---

References

Discussion: https://github.com/rails/rails/pull/13139
Deprecation (4.2.0): https://github.com/rails/rails/pull/13392
Removal (5.0.0): https://github.com/rails/rails/commit/481e49c64f790e46f4aff3ed539ed227d2eb46cb

**Comment by kenchan0130** [comment]
ops, I'm sorry, I mistook referenced branch.
